// <auto-generated />
namespace ASP.NET_MVC_EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BookDbScripts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookDbScripts));
        
        string IMigrationMetadata.Id
        {
            get { return "202107311227172_BookDbScripts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
